### PR TITLE
Added option to handle shirt size option

### PR DESCRIPTION
**Pull request by vinuphilip**
### Description

This change is to support the handling of shirt size option of vRA, so that users can enter the shirt size value (combination of CPU, RAM and Storage) of the desired VM they wish to provision, provided the blueprint they wish to provision has the shirt size option set up.

### Issues Resolved

None. This is just an enhancement

### Check List

- [Y] All tests pass.
- [Y] All style checks pass.
- [Y] Functionality includes testing.
- [Y] Functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by vinuphilip** [comment]
Signed-off-by: Vinu Philip <vinu.philip@gmail.com>

**Comment by vinuphilip** [comment]
Also password credential has been masked in Debug mode

Signed-off-by: Vinu Philip <vinu.philip@gmail.com>

**Comment by mwrock** [comment]
Hi @vinuphilip can you recommit with a DCO. It looks like you added it as a github comment but it needs to be in the actual commit. See https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco for details.

**Comment by vinuphilip** [comment]
hey @mwrock - i have again did a re-commit with minor changes to readme notes with DCO sign off in the commit message. Would it work

**Comment by mwrock** [comment]
The DCO check is still failing. Thats probably because the original commit without the DCO is still in the PR. I would `git reset` to the sha before that commit and then commit your changes again in a single commit (making sure it is signed) and then force push. That should do it.

**Pull request closed without merging**
