### PR TITLE
adds ability to specify additional params to catalog request

### PR DESCRIPTION
**Pull request by logicminds**

### CODE REVIEW

**Comment by jjasghar** [comment]
Can you add some documentation around this, please?

**Comment by logicminds** [comment]
I'll update soon with docs and usage.

**Comment by jjasghar** [comment]
Awesome, looking forward to it. As soon as this is done, I'll release it to ruby gems.

**Comment by jjasghar** [comment]
Any update on the docs here?

**Comment by logicminds** [comment]
I started it and got sidetracked.  Will finish this week.

**Comment by logicminds** [comment]
@jjasghar just pushed.  Hopefully the docs make sense.

https://github.com/logicminds/vmware-vra-gem/blob/params/README.md#creating-a-request-from-a-yaml-or-json-payload

Let me know if I should make changes.

**Pull request merged**
