### PR TITLE
mask secret values in text representation of client

### PR DESCRIPTION
**Pull request by rubytester**
Similar to octokit.rb
https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client.rb#L113

do not leak password nor token in text representation of client.

This helps me to demo this gem with pry without everybody seeing my password or token. 

Thank you

### CODE REVIEW

**Comment by adamleff** [comment]
Hi, @rubytester!  Thanks for using the gem, and thanks for your contribution!

I think this change is a good idea, but I'd like to suggest a few small changes before I merge it:

 * can you change your tests to use #include instead of #match?  #match expects a RegEx, so rspec is currently griping about redundant `*` characters:

```
/Users/aleff/.chefdk/gem/ruby/2.1.0/gems/rspec-expectations-3.3.0/lib/rspec/matchers/built_in/match.rb:25: warning: regular expression has redundant nested repeat operator '*': /@bearer_token=\"********\"/
```

You can make these go away by changing your tests to this:

```
expect(client.inspect).to include('@password="********"')
```

 * I think we should add an `attr_reader :password` to the Client class so that a user can still interrogate the password for troubleshooting purposes.  Now that it's gone from #inspect, there's no way of seeing it anymore.  This way it's still masked but a user can still get it if they need to.

What do you think?

**Comment by rubytester** [comment]
Hi, the gem is great, thanks. I am using it for our internal vRealize (about 120 machines)

I changed the test (duh, of course it makes sense, I didn't think about the `match` behaviour) 

I would not add `attr_reader :password`. If you really, really need it you can always get it with `client.instance_variable_get(:@password)`, so I would not add it the accessor in the public api.

I also realize that this line is ugly: 
`inspected.gsub! "@password=\"#{@password}\"", "@password=\"#{mask}\"" if @password`
a cleaner way would be to do this:
`inspected.gsub! @password, mask if @password`

But the ugly part prevents you from knowing that the string 'password' is used as a value for password, so the ugly implementation is not to leak the string 'password' but if people don't really care I can make a cleaner way and be done with it. 

the test would then change to 

`expect(client.inspect).to include('@********="********"')`

Ugly? or cleaner way?

**Comment by adamleff** [comment]
@rubytester - I think I have a better idea.  What if we delegate the password handling to a separate class which re-implements #inspect and #to_s to just return "*******" but implements a #value method that actually returns the real value?

There are other API client gems that I'm writing that would benefit from this, and I can't find anything that does something similar on RubyGems, so I'm going to write a gem that does this today and send up another PR for this project that uses it to show what I'm talking about.  That way, we don't have to actually manipulate the client object's inspect/string representation at all, and we'll have something more re-usable.  It will also avoid the "what if the password is 'password'" issue.

Let me know your thoughts.  Glad you like and are using the gem!

**Comment by adamleff** [comment]
@rubytester Check out this PR: https://github.com/chef-partners/vmware-vra-gem/pull/9

Rather than hacking the client object's #inspect method, I broke out the sensitive strings into their own class.  Take a look and let me know what you think.  If that works for you, I'd like to close this out and I'll get the other one merged.

**Comment by rubytester** [comment]
It's ok with me. I just wanted to have the 'simplest' thing but if you feel separate gem that masks secrets is needed then go for it. 
Thanks, I will close this PR and looking forward to new gem version with masking.

**Comment by adamleff** [comment]
@rubytester I think this is a simple approach too, but more importantly to me, it's reusable with other client gems that will have the same problem, and perhaps even in core Chef!

Thanks again for your contribution, and for using the gem!  Watch that other PR and I'll try to release it today or tomorrow.

**Comment by rubytester** [comment]
Great. Thanks.

**Comment by adamleff** [comment]
@rubytester PR #9 has been merged, and I've cut a v1.1.0 release and pushed it up to RubyGems.  Thanks again for your help!

**Pull request closed without merging**
